name: apod
description: Astronomy Picture of the Day

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  kiwi: ^0.1.0
  http: ^0.12.0+1
  shared_preferences: ^0.5.1+1
  cached_network_image: ^0.6.0+1
  webview_flutter: ^0.3.3+1
  transparent_image: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  - assets/drawables/
  - environment.json
  fonts:
  - family: Nasa
    fonts:
    - asset: assets/fonts/nasa.ttf